### ISSUE TITLE
Ad banner not displaying anymore

### ISSUE THREAD

**Issue by ramsestom** [SempaiGames/openfl-admob#11]
I have an android project that uses the openfl-admob library to display an admob banner.
This used to work correctly but since a month or so, the ad banner do not display anymore (whithout any change in the code of the class requesting it).
I have of course updated the google sdk API to the latest, so as the openfl-admob lib, but it do not fixed the issue. The problem is that I do not see any error trace message in the output console. So I really don't know what is going on. I have another android  project that also use openfl-admob but for which the ad banner is correctly displayed. So I tried to use the same bannerID in both projects to see wheter the issue could be related to a wrong/deprecated ID. But the problematic project still do not display any ad whereas the other one is working correctly. Both classes that makes call to the AdMob.showBanner() are really similar in each project so I really don't understand why it is working in one and not the other. Also, I tried to replace the AdMob.showBanner() by an AdMob.showInterstitial() call but the ad do not show either. So it looks like whatever the type of ad I am trying to display, it is working in one project but not in the other.
Hence my question is: Is there any way to track in detail why the ad is not displayed? Is there a verbose mode that can be activated and show me in detail the calls the openfl-admob library is doing (to see if the ad is correctly loaded and if it is just a display problem or something else)?

**Comment by fbricker** [comment]
Hi, have you tried using "adb logcat" to get more detailed logs on the issue?

You can do this by using the android monitor tool or by executing "adb logcat" command while you phone is connected to your computer and in debug mode.

**Comment by ramsestom** [comment]
Yes. actually this is the same as using the "-debug" flag in the lime command line.
The problem is that I have an overflow of message of the type:
W/qcom_sensors_hal(  595): hal_timestamp_calc: Adjusting timestamp for rollover: 1438044606304179268, -3
that never stops (~50 of these messages per seconds) so it is impossible to see if there is any other error message among them.

**Comment by fbricker** [comment]
Judging by this part of the logs:
```
W/Ads ( 3147): Received error HTTP response code: 403
D/MainResourceLoader( 3147): load url:about:blank
W/qcom_sensors_hal( 595): hal_timestamp_calc: Adjusting timestamp for rollover: 1438044843573979169, -3
W/Ads ( 5052): There was a problem getting an ad response. ErrorCode: 0
W/Ads ( 5052): Failed to load ad: 0
D/AdMobEx ( 5052): Fail to get Banner: 0
D/MainResourceLoader( 5052): load url:about:blank
```
It looks like it's an AdMob or network issue. I'm testing here compiled with last version of everything (openfl, lime, etc...) and it's working on my games.

Here goes some ideas to check:
1. Is it possible that admob has blocked your game / banners for some reason?
2. Are you using some kind of AdBlock on your devices?
3. Can you test the game on another cellphone that has a different google account?
4. Have you tried enabling test ads? (calling AdMob.enableTestingAds();)

**Comment by ramsestom** [comment]
Here goes some ideas to check:
1. Is it possible that admob has blocked your game / banners for some reason?
It is alway possible but I higly doubt it as it is a game in developpment that I nver published anyware and always only runned on my test device

2. Are you using some kind of AdBlock on your devices?
No. And I tested it with 2 different 4G LTE providers so it is not my network provider that block admob ads either.

3. Can you test the game on another cellphone that has a different google account?
I tested it on different devices with different android versions but I think all these devices share the same google account...
Anyway, I think point 2 and 3 can be eliminated as, as said, openf-admob is working with another app running on exactly the same device and the same google account.

4. Have you tried enabling test ads? (calling AdMob.enableTestingAds();)
I just tried and nothing changed.


I think my issue is more related to a missconfiguration in my app (or on my admob account even if I did not changed anything in it before it stopped working) as my other app using openfl-admob is able to display ad banners. But I really don't know what could be wrong as bothe have really similar code for the class displaying these ads (a menu class with just an app logo and some buttons). So I think I would have to create a minimalist small test app and try to track where could be the issue.

**Comment by fbricker** [comment]
That will be the best way to go... please let me know as soon as you have more information :)

**Comment by ramsestom** [comment]
Well something really strange happened. I added a button to have access to google play leadership in my menu page (where the add is supposed to be displayed) using your openfl-gpg lib. When I clicked on this button, the app told me that I had to update to the latest google play service on my device. What I did. And now, the banner ads are working again in my app! So it looks like somehow, the problem was linked to a deprecated google play service on my device (I still don't know why my other app had no issue to display banner ads with the old google play service installed...).

**Comment by fbricker** [comment]
Nice, good to know it's working.
PS: I'll check this showBanner() on first call soon :+1:

**Comment by DleanJeans** [comment]
In case someone having this problem
You still have to call showBanner() twice

**Comment by fbricker** [comment]
Hi, are you assigned a function to onInterstitialEvent ?
Something like this, should help you find out what's going on:

```haxe
AdMob.onInterstitialEvent = function(event:String){
    trace("Interstitial Event: "+event);
}
```

Please let us know what output do you get when assigning this function 👍

**Comment by DleanJeans** [comment]
Sorry! My bad! I think the bug was on my side of code.
